int64 id
geometry_msgs/Point left_lane_boundary  # the left boundary of the late at the gate
geometry_msgs/Point right_lane_boundary # the right boundary of the late at the gate
float32 lane_center_point 
float32 left_pole  # the left boundary of the gate
float32 right_pole # the right boundary of the gate
float32 prefered_path_point # prefered point where the car passes the gate
float32 prefered_path_weight # weight for prefered point where the car passes the gate
